import type { NextConfig } from 'next';

const nextConfig: NextConfig = {
  // In production this allowed exactly one remote image host, scoped by upload
  // path rather than bare hostname, so a compromised config could not pull
  // images from elsewhere.
  //
  // In the showcase all imagery is local placeholder SVG generated by
  // `npm run seed`, so no remote patterns are configured at all. A tightened
  // allowlist is the safer default: an absent entry blocks remote fetches
  // outright rather than permitting them.
  images: {
    remotePatterns: [],
  },

  async headers() {
    return [
      {
        // Public assets are content-stable by convention, so let the browser
        // and edge hold them for a year. Combined with next/image's immutable,
        // content-hashed optimiser URLs, repeat visits cost effectively zero
        // image bandwidth. Replace a file rather than editing it, so the URL
        // changes and the cache entry is replaced rather than served stale.
        source: '/images/:path*',
        headers: [
          {
            key: 'Cache-Control',
            value:
              'public, max-age=31536000, immutable, stale-while-revalidate=86400',
          },
        ],
      },
    ];
  },
};

export default nextConfig;
